#!/bin/bash

architecture=$(dpkg --print-architecture)
device=$(uname -o)
SH=$(basename $SHELL)

main()
{

    $CP system/$DIR/trash.${arch} $PREFIX/bin/trash
    if [[ ${SH} == *"bash"* ]]
    then
    echo "alias rm=\"trash \$@\"" >> ~/.bashrc
    elif [[ ${SH} == *"zsh"* ]]
    then
    echo "alias rm=\"trash \$@\"" >> ~/.zshrc
    fi
    echo "Installation complete.
    New parameters ::
    rm --about
    rm --clean
    rm --find <name>
    rm --recover <name>"
}

if [[ ${device} == *"Android"* ]]
then
CP=cp
DIR=termux
case "$architecture" in
    aarch64)
        arch=aarch64
        ;;
    arm)
        arch=arm
        ;;
    armhf)
        arch=arm
        ;;
    esac

    main
else
    CP="sudo cp"
    DIR=linux
    PREFIX=/usr
    case "$architecture" in
    amd64)
        arch=amd64
        ;;
    arm64)
        arch=arm64
        ;;
    esac

    main
fi


